// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_LABEL1_H
#define _UI_COMP_LABEL1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Label1
#define UI_COMP_LABEL1_LABEL1 0
#define _UI_COMP_LABEL1_NUM 1
lv_obj_t * ui_Label1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
