// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_BLACK_H
#define UI_BLACK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Black
extern void ui_Black_screen_init(void);
extern void ui_Black_screen_destroy(void);
extern lv_obj_t * ui_Black;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Black;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

