// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Black;
lv_obj_t * ui_Black = NULL;
// event funtions

// build funtions

void ui_Black_screen_init(void)
{
    ui_Black = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Black, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Black = ui_Black;

}

void ui_Black_screen_destroy(void)
{
    if(ui_Black) lv_obj_del(ui_Black);

    // NULL screen variables
    uic_Black = NULL;
    ui_Black = NULL;

}
