// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_CARMAIN_H
#define UI_CARMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CarMain
extern void ui_CarMain_screen_init(void);
extern void ui_CarMain_screen_destroy(void);
extern lv_obj_t * ui_CarMain;
extern lv_obj_t * ui_PressureC1;
extern lv_obj_t * ui_PressureC2;
extern lv_obj_t * ui_PressureC3;
extern lv_obj_t * ui_PressureC4;
extern lv_obj_t * ui_UnitC;
extern lv_obj_t * ui_AlertC1;
extern lv_obj_t * ui_AlertC2;
extern lv_obj_t * ui_TempTextC1;
extern lv_obj_t * ui_TempTextC2;
extern lv_obj_t * ui_TempTextC3;
extern lv_obj_t * ui_TempTextC4;
extern lv_obj_t * ui_BatteryBarC1;
extern lv_obj_t * ui_BatteryBarC2;
extern lv_obj_t * ui_BatteryBarC3;
extern lv_obj_t * ui_BatteryBarC4;
extern lv_obj_t * ui_TempIconC1;
extern lv_obj_t * ui_BatteryC1;
extern lv_obj_t * ui_BatteryC2;
extern lv_obj_t * ui_BatteryC3;
extern lv_obj_t * ui_BatteryC4;
extern lv_obj_t * ui_TPMSiconC1;
extern lv_obj_t * ui_TPMSiconC2;
extern lv_obj_t * ui_TPMSiconC3;
extern lv_obj_t * ui_TPMSiconC4;
extern lv_obj_t * ui_BatteryTextC1;
extern lv_obj_t * ui_BatteryTextC2;
extern lv_obj_t * ui_BatteryTextC3;
extern lv_obj_t * ui_BatteryTextC4;
extern lv_obj_t * ui_BTiconC1;
extern lv_obj_t * ui_BTiconC2;
extern lv_obj_t * ui_BTiconC3;
extern lv_obj_t * ui_BTiconC4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

