// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_CarMain = NULL;
lv_obj_t * ui_PressureC1 = NULL;
lv_obj_t * ui_PressureC2 = NULL;
lv_obj_t * ui_PressureC3 = NULL;
lv_obj_t * ui_PressureC4 = NULL;
lv_obj_t * ui_UnitC = NULL;
lv_obj_t * ui_AlertC1 = NULL;
lv_obj_t * ui_AlertC2 = NULL;
lv_obj_t * ui_TempTextC1 = NULL;
lv_obj_t * ui_TempTextC2 = NULL;
lv_obj_t * ui_TempTextC3 = NULL;
lv_obj_t * ui_TempTextC4 = NULL;
lv_obj_t * ui_BatteryBarC1 = NULL;
lv_obj_t * ui_BatteryBarC2 = NULL;
lv_obj_t * ui_BatteryBarC3 = NULL;
lv_obj_t * ui_BatteryBarC4 = NULL;
lv_obj_t * ui_TempIconC1 = NULL;
lv_obj_t * ui_BatteryC1 = NULL;
lv_obj_t * ui_BatteryC2 = NULL;
lv_obj_t * ui_BatteryC3 = NULL;
lv_obj_t * ui_BatteryC4 = NULL;
lv_obj_t * ui_TPMSiconC1 = NULL;
lv_obj_t * ui_TPMSiconC2 = NULL;
lv_obj_t * ui_TPMSiconC3 = NULL;
lv_obj_t * ui_TPMSiconC4 = NULL;
lv_obj_t * ui_BatteryTextC1 = NULL;
lv_obj_t * ui_BatteryTextC2 = NULL;
lv_obj_t * ui_BatteryTextC3 = NULL;
lv_obj_t * ui_BatteryTextC4 = NULL;
lv_obj_t * ui_BTiconC1 = NULL;
lv_obj_t * ui_BTiconC2 = NULL;
lv_obj_t * ui_BTiconC3 = NULL;
lv_obj_t * ui_BTiconC4 = NULL;
// event funtions

// build funtions

void ui_CarMain_screen_init(void)
{
    ui_CarMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CarMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PressureC1 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_PressureC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressureC1, -39);
    lv_obj_set_y(ui_PressureC1, -53);
    lv_obj_set_align(ui_PressureC1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureC1, "35.0");
    ui_object_set_themeable_style_property(ui_PressureC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_PressureC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_PressureC1, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureC2 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_PressureC2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureC2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressureC2, -39);
    lv_obj_set_y(ui_PressureC2, 53);
    lv_obj_set_align(ui_PressureC2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureC2, "35.0");
    ui_object_set_themeable_style_property(ui_PressureC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_PressureC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_PressureC2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureC3 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_PressureC3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureC3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressureC3, 39);
    lv_obj_set_y(ui_PressureC3, -52);
    lv_obj_set_align(ui_PressureC3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureC3, "35.0");
    ui_object_set_themeable_style_property(ui_PressureC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_PressureC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_PressureC3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PressureC4 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_PressureC4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressureC4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressureC4, 39);
    lv_obj_set_y(ui_PressureC4, 52);
    lv_obj_set_align(ui_PressureC4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressureC4, "35.0");
    ui_object_set_themeable_style_property(ui_PressureC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_PressureC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_PressureC4, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnitC = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_UnitC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnitC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UnitC, 0);
    lv_obj_set_y(ui_UnitC, -82);
    lv_obj_set_align(ui_UnitC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UnitC, "PSI");
    ui_object_set_themeable_style_property(ui_UnitC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_UnitC, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_AlertC1 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_AlertC1, &ui_img_alert_png);
    lv_obj_set_width(ui_AlertC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlertC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlertC1, 3);
    lv_obj_set_y(ui_AlertC1, 93);
    lv_obj_set_align(ui_AlertC1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AlertC1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AlertC1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AlertC2 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_AlertC2, &ui_img_alert_png);
    lv_obj_set_width(ui_AlertC2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlertC2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlertC2, 95);
    lv_obj_set_y(ui_AlertC2, 0);
    lv_obj_set_align(ui_AlertC2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AlertC2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AlertC2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempTextC1 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_TempTextC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempTextC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempTextC1, -38);
    lv_obj_set_y(ui_TempTextC1, -26);
    lv_obj_set_align(ui_TempTextC1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempTextC1, "23.2 C");
    ui_object_set_themeable_style_property(ui_TempTextC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TempTextC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_TempTextC2 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_TempTextC2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempTextC2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempTextC2, -38);
    lv_obj_set_y(ui_TempTextC2, 26);
    lv_obj_set_align(ui_TempTextC2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempTextC2, "23.2 C");
    ui_object_set_themeable_style_property(ui_TempTextC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TempTextC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_TempTextC3 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_TempTextC3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempTextC3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempTextC3, 38);
    lv_obj_set_y(ui_TempTextC3, -26);
    lv_obj_set_align(ui_TempTextC3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempTextC3, "23.2 C");
    ui_object_set_themeable_style_property(ui_TempTextC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TempTextC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_TempTextC4 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_TempTextC4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempTextC4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempTextC4, 38);
    lv_obj_set_y(ui_TempTextC4, 26);
    lv_obj_set_align(ui_TempTextC4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempTextC4, "23.2 C");
    ui_object_set_themeable_style_property(ui_TempTextC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TempTextC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_BatteryBarC1 = lv_bar_create(ui_CarMain);
    lv_bar_set_range(ui_BatteryBarC1, 0, 65);
    lv_bar_set_value(ui_BatteryBarC1, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBarC1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBarC1, 39);
    lv_obj_set_height(ui_BatteryBarC1, 10);
    lv_obj_set_x(ui_BatteryBarC1, -37);
    lv_obj_set_y(ui_BatteryBarC1, -11);
    lv_obj_set_align(ui_BatteryBarC1, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BatteryBarC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Standard);
    ui_object_set_themeable_style_property(ui_BatteryBarC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Standard);

    ui_object_set_themeable_style_property(ui_BatteryBarC1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bright);
    ui_object_set_themeable_style_property(ui_BatteryBarC1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bright);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BatteryBarC1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BatteryBarC1,
                                                                                                   lv_obj_get_style_pad_right(ui_BatteryBarC1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_BatteryBarC2 = lv_bar_create(ui_CarMain);
    lv_bar_set_range(ui_BatteryBarC2, 0, 65);
    lv_bar_set_value(ui_BatteryBarC2, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBarC2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBarC2, 39);
    lv_obj_set_height(ui_BatteryBarC2, 10);
    lv_obj_set_x(ui_BatteryBarC2, -37);
    lv_obj_set_y(ui_BatteryBarC2, 11);
    lv_obj_set_align(ui_BatteryBarC2, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BatteryBarC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Standard);
    ui_object_set_themeable_style_property(ui_BatteryBarC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Standard);

    ui_object_set_themeable_style_property(ui_BatteryBarC2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bright);
    ui_object_set_themeable_style_property(ui_BatteryBarC2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bright);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BatteryBarC2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BatteryBarC2,
                                                                                                   lv_obj_get_style_pad_right(ui_BatteryBarC2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_BatteryBarC3 = lv_bar_create(ui_CarMain);
    lv_bar_set_range(ui_BatteryBarC3, 0, 65);
    lv_bar_set_value(ui_BatteryBarC3, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBarC3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBarC3, 39);
    lv_obj_set_height(ui_BatteryBarC3, 10);
    lv_obj_set_x(ui_BatteryBarC3, 37);
    lv_obj_set_y(ui_BatteryBarC3, -11);
    lv_obj_set_align(ui_BatteryBarC3, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BatteryBarC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Standard);
    ui_object_set_themeable_style_property(ui_BatteryBarC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Standard);

    ui_object_set_themeable_style_property(ui_BatteryBarC3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bright);
    ui_object_set_themeable_style_property(ui_BatteryBarC3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bright);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BatteryBarC3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BatteryBarC3,
                                                                                                   lv_obj_get_style_pad_right(ui_BatteryBarC3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_BatteryBarC4 = lv_bar_create(ui_CarMain);
    lv_bar_set_range(ui_BatteryBarC4, 0, 65);
    lv_bar_set_value(ui_BatteryBarC4, 10, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBarC4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBarC4, 39);
    lv_obj_set_height(ui_BatteryBarC4, 10);
    lv_obj_set_x(ui_BatteryBarC4, 37);
    lv_obj_set_y(ui_BatteryBarC4, 11);
    lv_obj_set_align(ui_BatteryBarC4, LV_ALIGN_CENTER);
    ui_object_set_themeable_style_property(ui_BatteryBarC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Standard);
    ui_object_set_themeable_style_property(ui_BatteryBarC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Standard);

    ui_object_set_themeable_style_property(ui_BatteryBarC4, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Bright);
    ui_object_set_themeable_style_property(ui_BatteryBarC4, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Bright);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BatteryBarC4, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BatteryBarC4,
                                                                                                   lv_obj_get_style_pad_right(ui_BatteryBarC4, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_TempIconC1 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_TempIconC1, &ui_img_temp_png);
    lv_obj_set_width(ui_TempIconC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempIconC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempIconC1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempIconC1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TempIconC1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_TempIconC1, 4);
    lv_image_set_scale(ui_TempIconC1, 180);

    ui_BatteryC1 = lv_arc_create(ui_CarMain);
    lv_obj_set_width(ui_BatteryC1, 220);
    lv_obj_set_height(ui_BatteryC1, 220);
    lv_obj_set_align(ui_BatteryC1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BatteryC1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_value(ui_BatteryC1, 80);
    lv_arc_set_bg_angles(ui_BatteryC1, 205, 255);
    ui_object_set_themeable_style_property(ui_BatteryC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Standard);
    ui_object_set_themeable_style_property(ui_BatteryC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Standard);
    lv_obj_set_style_arc_width(ui_BatteryC1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BatteryC1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_BatteryC1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Bright);
    ui_object_set_themeable_style_property(ui_BatteryC1, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Bright);

    ui_object_set_themeable_style_property(ui_BatteryC1, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_BatteryC1, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_shadow_width(ui_BatteryC1, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BatteryC1, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BatteryC1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BatteryC1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BatteryC1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BatteryC1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BatteryC2 = lv_arc_create(ui_CarMain);
    lv_obj_set_width(ui_BatteryC2, 220);
    lv_obj_set_height(ui_BatteryC2, 220);
    lv_obj_set_align(ui_BatteryC2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BatteryC2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_value(ui_BatteryC2, 80);
    lv_arc_set_bg_angles(ui_BatteryC2, 105, 155);
    ui_object_set_themeable_style_property(ui_BatteryC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Standard);
    ui_object_set_themeable_style_property(ui_BatteryC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Standard);
    lv_obj_set_style_arc_width(ui_BatteryC2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BatteryC2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_BatteryC2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Bright);
    ui_object_set_themeable_style_property(ui_BatteryC2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Bright);

    ui_object_set_themeable_style_property(ui_BatteryC2, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_BatteryC2, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_shadow_width(ui_BatteryC2, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BatteryC2, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BatteryC2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BatteryC2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BatteryC2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BatteryC2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BatteryC3 = lv_arc_create(ui_CarMain);
    lv_obj_set_width(ui_BatteryC3, 220);
    lv_obj_set_height(ui_BatteryC3, 220);
    lv_obj_set_align(ui_BatteryC3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BatteryC3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_value(ui_BatteryC3, 80);
    lv_arc_set_bg_angles(ui_BatteryC3, 285, 335);
    ui_object_set_themeable_style_property(ui_BatteryC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Standard);
    ui_object_set_themeable_style_property(ui_BatteryC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Standard);
    lv_obj_set_style_arc_width(ui_BatteryC3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BatteryC3, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_BatteryC3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Bright);
    ui_object_set_themeable_style_property(ui_BatteryC3, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Bright);

    ui_object_set_themeable_style_property(ui_BatteryC3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_BatteryC3, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_shadow_width(ui_BatteryC3, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BatteryC3, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BatteryC3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BatteryC3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BatteryC3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BatteryC3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BatteryC4 = lv_arc_create(ui_CarMain);
    lv_obj_set_width(ui_BatteryC4, 220);
    lv_obj_set_height(ui_BatteryC4, 220);
    lv_obj_set_align(ui_BatteryC4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BatteryC4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_arc_set_value(ui_BatteryC4, 80);
    lv_arc_set_bg_angles(ui_BatteryC4, 25, 75);
    ui_object_set_themeable_style_property(ui_BatteryC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Standard);
    ui_object_set_themeable_style_property(ui_BatteryC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Standard);
    lv_obj_set_style_arc_width(ui_BatteryC4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_BatteryC4, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_BatteryC4, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Bright);
    ui_object_set_themeable_style_property(ui_BatteryC4, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Bright);

    ui_object_set_themeable_style_property(ui_BatteryC4, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_BatteryC4, LV_PART_KNOB | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_shadow_width(ui_BatteryC4, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BatteryC4, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_BatteryC4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BatteryC4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BatteryC4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BatteryC4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TPMSiconC1 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_TPMSiconC1, &ui_img_tpmsblack_png);
    lv_obj_set_width(ui_TPMSiconC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TPMSiconC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TPMSiconC1, -39);
    lv_obj_set_y(ui_TPMSiconC1, -79);
    lv_obj_set_align(ui_TPMSiconC1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TPMSiconC1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TPMSiconC1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_TPMSiconC1, 220);

    ui_TPMSiconC2 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_TPMSiconC2, &ui_img_tpmsblack_png);
    lv_obj_set_width(ui_TPMSiconC2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TPMSiconC2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TPMSiconC2, -39);
    lv_obj_set_y(ui_TPMSiconC2, 79);
    lv_obj_set_align(ui_TPMSiconC2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TPMSiconC2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TPMSiconC2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_TPMSiconC2, 220);

    ui_TPMSiconC3 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_TPMSiconC3, &ui_img_tpmsblack_png);
    lv_obj_set_width(ui_TPMSiconC3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TPMSiconC3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TPMSiconC3, 39);
    lv_obj_set_y(ui_TPMSiconC3, -79);
    lv_obj_set_align(ui_TPMSiconC3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TPMSiconC3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TPMSiconC3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_TPMSiconC3, 220);

    ui_TPMSiconC4 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_TPMSiconC4, &ui_img_tpmsblack_png);
    lv_obj_set_width(ui_TPMSiconC4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TPMSiconC4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TPMSiconC4, 39);
    lv_obj_set_y(ui_TPMSiconC4, 79);
    lv_obj_set_align(ui_TPMSiconC4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TPMSiconC4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TPMSiconC4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_TPMSiconC4, 220);

    ui_BatteryTextC1 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_BatteryTextC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryTextC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryTextC1, -92);
    lv_obj_set_y(ui_BatteryTextC1, -23);
    lv_obj_set_align(ui_BatteryTextC1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextC1, "100%");
    ui_object_set_themeable_style_property(ui_BatteryTextC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_BatteryTextC1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_BatteryTextC2 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_BatteryTextC2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryTextC2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryTextC2, -92);
    lv_obj_set_y(ui_BatteryTextC2, 23);
    lv_obj_set_align(ui_BatteryTextC2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextC2, "100%");
    ui_object_set_themeable_style_property(ui_BatteryTextC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_BatteryTextC2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_BatteryTextC3 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_BatteryTextC3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryTextC3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryTextC3, 92);
    lv_obj_set_y(ui_BatteryTextC3, -23);
    lv_obj_set_align(ui_BatteryTextC3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextC3, "100%");
    ui_object_set_themeable_style_property(ui_BatteryTextC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_BatteryTextC3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_BatteryTextC4 = lv_label_create(ui_CarMain);
    lv_obj_set_width(ui_BatteryTextC4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryTextC4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryTextC4, 92);
    lv_obj_set_y(ui_BatteryTextC4, 23);
    lv_obj_set_align(ui_BatteryTextC4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryTextC4, "100%");
    ui_object_set_themeable_style_property(ui_BatteryTextC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_BatteryTextC4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_BTiconC1 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_BTiconC1, &ui_img_bton_png);
    lv_obj_set_width(ui_BTiconC1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTiconC1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTiconC1, -76);
    lv_obj_set_y(ui_BTiconC1, -52);
    lv_obj_set_align(ui_BTiconC1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTiconC1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTiconC1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BTiconC1, 140);

    ui_BTiconC2 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_BTiconC2, &ui_img_bton_png);
    lv_obj_set_width(ui_BTiconC2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTiconC2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTiconC2, -76);
    lv_obj_set_y(ui_BTiconC2, 52);
    lv_obj_set_align(ui_BTiconC2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTiconC2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTiconC2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BTiconC2, 140);

    ui_BTiconC3 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_BTiconC3, &ui_img_bton_png);
    lv_obj_set_width(ui_BTiconC3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTiconC3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTiconC3, 76);
    lv_obj_set_y(ui_BTiconC3, -52);
    lv_obj_set_align(ui_BTiconC3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTiconC3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTiconC3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BTiconC3, 140);

    ui_BTiconC4 = lv_image_create(ui_CarMain);
    lv_image_set_src(ui_BTiconC4, &ui_img_bton_png);
    lv_obj_set_width(ui_BTiconC4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTiconC4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTiconC4, 76);
    lv_obj_set_y(ui_BTiconC4, 52);
    lv_obj_set_align(ui_BTiconC4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTiconC4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTiconC4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BTiconC4, 140);

}

void ui_CarMain_screen_destroy(void)
{
    if(ui_CarMain) lv_obj_del(ui_CarMain);

    // NULL screen variables
    ui_CarMain = NULL;
    ui_PressureC1 = NULL;
    ui_PressureC2 = NULL;
    ui_PressureC3 = NULL;
    ui_PressureC4 = NULL;
    ui_UnitC = NULL;
    ui_AlertC1 = NULL;
    ui_AlertC2 = NULL;
    ui_TempTextC1 = NULL;
    ui_TempTextC2 = NULL;
    ui_TempTextC3 = NULL;
    ui_TempTextC4 = NULL;
    ui_BatteryBarC1 = NULL;
    ui_BatteryBarC2 = NULL;
    ui_BatteryBarC3 = NULL;
    ui_BatteryBarC4 = NULL;
    ui_TempIconC1 = NULL;
    ui_BatteryC1 = NULL;
    ui_BatteryC2 = NULL;
    ui_BatteryC3 = NULL;
    ui_BatteryC4 = NULL;
    ui_TPMSiconC1 = NULL;
    ui_TPMSiconC2 = NULL;
    ui_TPMSiconC3 = NULL;
    ui_TPMSiconC4 = NULL;
    ui_BatteryTextC1 = NULL;
    ui_BatteryTextC2 = NULL;
    ui_BatteryTextC3 = NULL;
    ui_BatteryTextC4 = NULL;
    ui_BTiconC1 = NULL;
    ui_BTiconC2 = NULL;
    ui_BTiconC3 = NULL;
    ui_BTiconC4 = NULL;

}
