// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Unit;
extern lv_obj_t * ui_Pressure1;
extern lv_obj_t * ui_Pressure2;
extern lv_obj_t * ui_Battery1;
extern lv_obj_t * ui_Battery2;
extern lv_obj_t * ui_Busy;
extern lv_obj_t * ui_BatteryBar1;
extern lv_obj_t * ui_TempText1;
extern lv_obj_t * ui_TempText2;
extern lv_obj_t * ui_BatteryBar2;
extern lv_obj_t * ui_BatteryText1;
extern lv_obj_t * ui_BatteryText2;
extern lv_obj_t * ui_TPMSicon1;
extern lv_obj_t * ui_TPMSicon2;
extern lv_obj_t * ui_TempIcon1;
extern lv_obj_t * ui_TempIcon2;
extern lv_obj_t * ui_BTicon1;
extern lv_obj_t * ui_BTicon2;
extern lv_obj_t * ui_Alert1;
extern lv_obj_t * ui_Alert2;
extern lv_obj_t * ui_Unused1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Main;
extern lv_obj_t * uic_Unit;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

