// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Pair = NULL;
lv_obj_t * ui_PairOperation = NULL;
lv_obj_t * ui_PairSensorName = NULL;
lv_obj_t * ui_Status = NULL;
lv_obj_t * ui_PairBusy = NULL;
lv_obj_t * ui_PairTimeout = NULL;
lv_obj_t * ui_PressKey = NULL;
// event funtions

// build funtions

void ui_Pair_screen_init(void)
{
    ui_Pair = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Pair, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PairOperation = lv_label_create(ui_Pair);
    lv_obj_set_width(ui_PairOperation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PairOperation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PairOperation, -2);
    lv_obj_set_y(ui_PairOperation, -50);
    lv_obj_set_align(ui_PairOperation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PairOperation, "SEARCHING FOR SENSOR");

    ui_PairSensorName = lv_label_create(ui_Pair);
    lv_obj_set_width(ui_PairSensorName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PairSensorName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PairSensorName, 0);
    lv_obj_set_y(ui_PairSensorName, -23);
    lv_obj_set_align(ui_PairSensorName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PairSensorName, " - FRONT WHEEL -");

    ui_Status = lv_label_create(ui_Pair);
    lv_obj_set_width(ui_Status, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Status, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Status, 0);
    lv_obj_set_y(ui_Status, 4);
    lv_obj_set_align(ui_Status, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Status, "NOT YET FOUND");
    lv_obj_set_style_text_color(ui_Status, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Status, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PairBusy = lv_spinner_create(ui_Pair);
    //lv_spinner_set_anim_params(ui_PairBusy, 1000, 90);
    lv_obj_set_width(ui_PairBusy, 37);
    lv_obj_set_height(ui_PairBusy, 34);
    lv_obj_set_x(ui_PairBusy, 0);
    lv_obj_set_y(ui_PairBusy, 45);
    lv_obj_set_align(ui_PairBusy, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PairBusy, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_PairBusy, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_PairBusy, lv_color_hex(0x00FF24), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_PairBusy, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_PairBusy, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_PairBusy, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PairTimeout = lv_label_create(ui_Pair);
    lv_obj_set_width(ui_PairTimeout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PairTimeout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PairTimeout, 0);
    lv_obj_set_y(ui_PairTimeout, 87);
    lv_obj_set_align(ui_PairTimeout, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PairTimeout, "LEFT: 60s");

    ui_PressKey = lv_label_create(ui_Pair);
    lv_obj_set_width(ui_PressKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PressKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PressKey, 0);
    lv_obj_set_y(ui_PressKey, 44);
    lv_obj_set_align(ui_PressKey, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PressKey, "PRESS 'PAIR' BUTTON");
    lv_obj_add_flag(ui_PressKey, LV_OBJ_FLAG_HIDDEN);     /// Flags

}

void ui_Pair_screen_destroy(void)
{
    if(ui_Pair) lv_obj_del(ui_Pair);

    // NULL screen variables
    ui_Pair = NULL;
    ui_PairOperation = NULL;
    ui_PairSensorName = NULL;
    ui_Status = NULL;
    ui_PairBusy = NULL;
    ui_PairTimeout = NULL;
    ui_PressKey = NULL;

}
