// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_PAIR_H
#define UI_PAIR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Pair
extern void ui_Pair_screen_init(void);
extern void ui_Pair_screen_destroy(void);
extern lv_obj_t * ui_Pair;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Spinner4;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

