// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include <stdio.h>
#include "../ui.h"

// Embedded splash logo (C array instead of PNG to save RAM)
LV_IMAGE_DECLARE(ui_img_splashlogo);

lv_obj_t * uic_Spinner3;
lv_obj_t * uic_Splash;
lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Spinner3 = NULL;
// event funtions

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Splash, lv_color_hex(0x0E4308), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Splash, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Splash, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_Label2, lv_pct(100));
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 100);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "V0.0.1");
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Splash);
    lv_image_set_src(ui_Image2, &ui_img_splashlogo);  // Use embedded C array
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 0);
    lv_obj_set_y(ui_Image2, -24);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner3 = lv_spinner_create(ui_Splash);
    //lv_spinner_set_anim_params(ui_Spinner3, 1000, 90);
    lv_obj_set_width(ui_Spinner3, 37);
    lv_obj_set_height(ui_Spinner3, 34);
    lv_obj_set_x(ui_Spinner3, 0);
    lv_obj_set_y(ui_Spinner3, 45);
    lv_obj_set_align(ui_Spinner3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0x00FF24), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner3, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Spinner3, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    uic_Splash = ui_Splash;
    uic_Spinner3 = ui_Spinner3;

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    uic_Splash = NULL;
    ui_Splash = NULL;
    ui_Label2 = NULL;
    ui_Image2 = NULL;
    uic_Spinner3 = NULL;
    ui_Spinner3 = NULL;

}
