// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SPLASH_H
#define UI_SPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Splash
extern void ui_Splash_screen_init(void);
extern void ui_Splash_screen_destroy(void);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_VersionStr;
extern lv_obj_t * ui_LogoImg;
extern lv_obj_t * ui_SplashSpinner;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Splash;
extern lv_obj_t * uic_SplashSpinner;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

