// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_SplashSpinner;
lv_obj_t * uic_Splash;
lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_VersionStr = NULL;
lv_obj_t * ui_LogoImg = NULL;
lv_obj_t * ui_SplashSpinner = NULL;
// event funtions

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Splash, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Splash, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    ui_object_set_themeable_style_property(ui_Splash, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_GRAD_COLOR,
                                           _ui_theme_color_Bright);
    lv_obj_set_style_bg_main_stop(ui_Splash, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Splash, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionStr = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_VersionStr, lv_pct(100));
    lv_obj_set_height(ui_VersionStr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionStr, 0);
    lv_obj_set_y(ui_VersionStr, 100);
    lv_obj_set_align(ui_VersionStr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VersionStr, "V0.0.1");
    ui_object_set_themeable_style_property(ui_VersionStr, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_VersionStr, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_align(ui_VersionStr, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImg = lv_image_create(ui_Splash);
    lv_image_set_src(ui_LogoImg, &ui_img_1818877690);
    lv_obj_set_width(ui_LogoImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoImg, 0);
    lv_obj_set_y(ui_LogoImg, -24);
    lv_obj_set_align(ui_LogoImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_LogoImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SplashSpinner = lv_spinner_create(ui_Splash);
    //lv_spinner_set_anim_params(ui_SplashSpinner, 1000, 90);
    lv_obj_set_width(ui_SplashSpinner, 37);
    lv_obj_set_height(ui_SplashSpinner, 34);
    lv_obj_set_x(ui_SplashSpinner, 0);
    lv_obj_set_y(ui_SplashSpinner, 45);
    lv_obj_set_align(ui_SplashSpinner, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SplashSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_SplashSpinner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Standard);
    ui_object_set_themeable_style_property(ui_SplashSpinner, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Standard);
    lv_obj_set_style_arc_width(ui_SplashSpinner, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(ui_SplashSpinner, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR,
                                           _ui_theme_color_Bright);
    ui_object_set_themeable_style_property(ui_SplashSpinner, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_ARC_OPA,
                                           _ui_theme_alpha_Bright);
    lv_obj_set_style_arc_width(ui_SplashSpinner, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SplashSpinner, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    uic_Splash = ui_Splash;
    uic_SplashSpinner = ui_SplashSpinner;

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    uic_Splash = NULL;
    ui_Splash = NULL;
    ui_VersionStr = NULL;
    ui_LogoImg = NULL;
    uic_SplashSpinner = NULL;
    ui_SplashSpinner = NULL;

}
