// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/splashlogo-pms.png
lv_image_dsc_t ui_img_942102620 = {
    .header.w = 240,
    .header.h = 74,
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
};

void ui_img_942102620_load()
{
    ui_img_942102620.data = UI_LOAD_IMAGE("S:assets/ui_img_942102620.bin", 8957, 53280);
    ui_img_942102620.data_size = 53280;
}
