// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"


// IMAGE DATA: assets/tpmsblack.png
lv_image_dsc_t ui_img_tpmsblack_png = {
    .header.w = 32,
    .header.h = 32,
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
};

void ui_img_tpmsblack_png_load()
{
    ui_img_tpmsblack_png.data = UI_LOAD_IMAGE("S:assets/ui_img_tpmsblack_png.bin", 710, 3072);
    ui_img_tpmsblack_png.data_size = 3072;
}
