// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Splash.h"
#include "screens/ui_Main.h"
#include "screens/ui_Black.h"
#include "screens/ui_Pair.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES - Loaded from SPIFFS filesystem instead of embedded C arrays
// Image paths: S:/splashlogo-pms.png, S:/tpmsred.png, S:/tpmsyellow.png,
//              S:/temp.png, S:/BToff.png, S:/BTon.png, S:/idle.png,
//              S:/alert.png, S:/tpmsblack.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
