// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Background[3] = {0x14171B, 0x1B1414, 0x011127};
const ui_theme_variable_t _ui_theme_alpha_Background[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Text[3] = {0xFFFFFF, 0xFFB8B8, 0xBEBEBE};
const ui_theme_variable_t _ui_theme_alpha_Text[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Standard[3] = {0x004E12, 0x524141, 0x01006C};
const ui_theme_variable_t _ui_theme_alpha_Standard[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Bright[3] = {0x14D900, 0xA82424, 0x2830D8};
const ui_theme_variable_t _ui_theme_alpha_Bright[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Hot[3] = {0x2600FF, 0x2600FF, 0xFF0000};  
const ui_theme_variable_t _ui_theme_alpha_Hot[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

